package fr.unice.polytech.citadelles.enums;

public enum DistrictName {
    TEMPLE, CHURCH, MONASTERY, CITADEL, MANSION, CASTLE, PALACE, TAVERN, SHOP, MARKET, COUNTER, PORT, CITY_HALL, WATCH_TOWER, JAIL, BARRACKS, FORTRESS,
    HAUNTED_QUARTER, KEEP, LABORATORY, SMITHY, OBSERVATORY, GRAVEYARD, LIBRARY, SCHOOL_OF_MAGIC, UNIVERSITY, DRAGONGATE,
    NONE
}
