package fr.unice.polytech.citadelles.enums;

public enum DistrictName {
    TEMPLE, CHURCH, MONASTERY, CITADEL, MANSION, CASTLE, PALACE, TAVERN, SHOP, MARKET, COUNTER, PORT, CITY_HALL, WATCH_TOWER, JAIL, BARRACKS, FORTRESS,
    HAUNTEDQUARTER, KEEP, LABORATORY, SMITHY, OBSERVATORY, GRAVEYARD, LIBRARY, SCHOOLOFMAGIC, UNIVERSITY, DRAGONGATE,
    NONE
}
